MCU=atmega328p
F_CPU=8000000UL
TARGET=main
PROGRAMMER=stk500v1
PORT=/dev/ttyUSB0
BAUD=19200

all: build
build: $(TARGET).hex

$(TARGET).hex: $(TARGET).elf
	avr-objcopy -O ihex -R .eeprom $(TARGET).elf $(TARGET).hex


$(TARGET).elf: $(TARGET).c
	avr-g++ -mmcu=atmega328p -Os -D F_CPU=8000000UL -o $(TARGET).elf $(TARGET).c

flash: $(TARGET).hex
	avrdude -C /etc/avrdude.conf -v -p $(MCU) -c stk500v1 -P $(PORT) -b $(BAUD) -U flash:w:$(TARGET).hex:i
clean: 
	rm $(TARGET).hex $(TARGET).elf
